import './globals.css'
import localFont from "@next/font/local";
import Header from '@/app/components/Header';


export const metadata = {
  title: 'AIIJ - Homepage',
  description: 'Generated by create next app',
}

const bebas = localFont({
  src: [
    {
      path: "../public/fonts/BebasNeue-Regular.ttf",
    },
  ],
  variable: "--font-heading",
});

const montserrat = localFont({
  variable: "--font-body",
  src: [
    {
      path: "../public/fonts/Montserrat-VariableFont_wght.ttf",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${bebas.variable} font-body bg-igren/[.02] h-full min-h-screen flex flex-col justify-between`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
